### ISSUE TITLE
Adding single/one WMS URL- by specifying layer service url and layer name

### ISSUE THREAD

**Issue by nareshnagamalle** [ckan/ckanext-geoview#22]
Dear Sir/Madam,

 With present ckanext-geoview we are not able to add single WMS Layer i.e for ex:
 WMS URL:   http://localhost:8080/geoserver/test/wms 
layer name:   'test:INDIA_STATE_250K'.

If we add getcability document ulr it is listing all the layrers, there is no mechanism to retrive single WMS layer details. Please add above capability to CKAN which will helpful create metadata/info regarding individual  layer

**Comment by mattfullerton** [comment]
:+1:

**Comment by mattfullerton** [comment]
In case it helps you can do this for WFS layers by selecting format WFS. For example for the WFS service:
http://geodienste-hamburg.de/HH_WFS_BWVI_opendata?REQUEST=GetCapabilities&SERVICE=WFS

You can get a single layer like this:
http://geodienste-hamburg.de/HH_WFS_BWVI_opendata?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=verkehr_baustellen_prod&srsName=EPSG:4326

**Comment by gjlawran** [comment]
@nareshnagamalle @mattfullerton We are able to use a single WMS layer with GeoView when we specify our getCapabiities request to GeoServer like this :

`https://<domain>/<layername>/ows?service=WMS&request=GetCapabilities`

Some examples can be viewed here:
http://catalogue.data.gov.bc.ca/dataset/landsat-image-catalogue-acquisition-dates-spatial-view-sii/resource/e4210a3d-2b42-4f3a-9f45-7a2042a9dc69

http://catalogue.data.gov.bc.ca/dataset/nts-250k-grid-digital-baseline-mapping-at-1-250-000-nts/resource/3a8bcd6d-2414-412f-ad9f-59c69d7ed165

**Comment by mattfullerton** [comment]
This is now possible for both WFS and WMS; thanks, I presume 🙂 , go to @pduchesne 

I've added a PR for docs:
https://github.com/ckan/ckanext-geoview/pull/56

Basically, add the WMS layer or WFS feature name with a "#" after the URL (WFS without qualifier)

@nareshnagamalle or @amercader - please close this

**Comment by guilhermeiablo** [comment]
I'm still unable to add single layers from WMS served by a Geoserver instance. Does anyone have any guidance on how to do it?

**Comment by mattfullerton** [comment]
Unfortunately, I don't really have access to a CKAN at the moment, but happy to try and help over a Google Hangout or similar.
