### ISSUE TITLE
Use resource views without proxy

### ISSUE THREAD

**Issue by neothemachine** [ckan/ckanext-geoview#29]
I'd like to use resource views of geoview without a proxy, which is ok since I require resources to have proper CORS headers. However, when I disable the resource_proxy extension, the WMS viewer still uses the proxy URL and gets a 404. The GeoJSON viewer uses the correct URL though.

**Comment by drnextgis** [comment]
I've faced with the same issue and [this](https://github.com/ckan/ckanext-geoview/pull/30) PR solved my problem.
