### ISSUE TITLE
WMS viewer JS error

### ISSUE THREAD

**Issue by bunnis** [ckan/ckanext-geoview#41]
When trying to view a WMS resource, using http://services.arcgisonline.com/arcgis/rest/Demographics/USE_Population_Density/MapServer/WMTS or other public wms

```
Uncaught TypeError: Cannot read property 'layers' of undefined(anonymous function) @ ol2_preview.js:5198OpenLayers.Request.GET.success @ ol2_preview.js:5043OpenLayers.Util.extend.runCallbacks @ ol2_preview.js:1871request.onreadystatechange @ ol2_preview.js:1867cXMLHttpRequest.dispatchEvent @ ol2_preview.js:1901fReadyStateChange @ ol2_preview.js:1904_object.onreadystatechange @ ol2_preview.js:1887
```

**Comment by pduchesne** [comment]
The service you are trying to use is a WMTS (tiling service), not a WMS.
The generic OpenLayers viewer you are using does not currently support the WMTS standard.

There's a leaflet-based WMTS plugin (named 'wmts_view') you can try.

**Comment by bunnis** [comment]
I thought they were the same! The plugin didn't automatically added the view,  so I manually added WMS as teh resource type. Ill tried it out, from WMS to WMTS and i got a 409 error, but I guess that is from the server! thank you

**Comment by bunnis** [comment]
Trying to use a WMS service (http://maps.ipma.pt/mapserv?map=/var/www/maps/forecasts/meteorology/arome_pt_2_10uv.map) produces the same error

**Comment by pduchesne** [comment]
Right, that's likely the service proxy that dumps the 'map' parameter when proxying the capabilities. 
FYI, that's specific to mapserver implementations.
Will look into fixing that.

**Comment by drnextgis** [comment]
It looks like duplicate of https://github.com/ckan/ckanext-geoview/issues/32

**Comment by drnextgis** [comment]
I've made PR https://github.com/ckan/ckanext-geoview/pull/42, please review it.

**Comment by pduchesne** [comment]
Thank you Denis, will merge, and apologizes for overlooking your fix.

**Comment by amercader** [comment]
Ups sorry @pduchesne I didn't saw you were meaning to review and merge #42

**Comment by pduchesne** [comment]
no worry, thank you @amercader .

One comment on this fix : stripping parameters in the js lib was on purpose, in the case where OGC services are registered with URL parameters like service, version, request, ... In that case, not stripping the parameters at all may cause such resources to fail being displayed.
I'll look into a "smart" stripping strategy.

**Comment by drnextgis** [comment]
@bunnis can we close this issue?

**Comment by bunnis** [comment]
Did this get fixed? I see you guys talk about merging PR but nothing got merged, so this issue's still open, right?

**Comment by drnextgis** [comment]
PR was merged: https://github.com/ckan/ckanext-geoview/commit/1e1121137c656a4f5f75e56276d41fd30de72ee4

**Comment by bunnis** [comment]
Ok! Thanks for the clarification.

**Comment by drnextgis** [comment]
@bunnis, are these changes solves your original issue?

**Comment by bunnis** [comment]
Just Tested and they do work, thank you
