### ISSUE TITLE
Request for a new tagged version and update pypi package?

### ISSUE THREAD

**Issue by jrods** [ckan/ckanext-geoview#45]
I don't know what the release schedule is like, but may i request a newer version be tagged and have the pypi package updated to the newest version? The current version on pypi is v0.0.9 (Nov 2015).

Reason being is our environment is limited to pypi packages and our own github repos.

https://github.com/bcgov/ckanext-bcgov/issues/95

**Comment by amercader** [comment]
@jrods just pushed 0.0.11 to the repo and pypi :snake:

**Comment by jrods** [comment]
Awesome, thanks a bunch @amercader , i appreciate it =)
