### ISSUE TITLE
MapQuest Discontinued Support

### ISSUE THREAD

**Issue by sc305495** [ckan/ckanext-geoview#46]
Per this article:
http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/  

This change seems to cause several, if not all, of the maps generated by this extension to no longer display as expected.  Instead, the geo layer still renders over the map as expected but the map tiles are replaced with an image stating:
As of July 11,2016 direct tile access has been discontinued.

Please visit our blog post for more information http://goo.gl/xB0xXt

Have questions?
Contact us:
developer-services@mapquest.com
Visit us:
developer.mapquest.com/forum

I don't think this is an issue with this extension per-say... but is there any plan for remediation to restore functionality here?

**Comment by TkTech** [comment]
See https://github.com/ckan/ckanext-spatial/issues/157 for discussion.

**Comment by sc305495** [comment]
Thank you, I should have read here
http://docs.ckan.org/projects/ckanext-spatial/en/latest/map-widgets.html, for a very quick fix I used the following to get the OSM standard style tiles.. more listed here http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames 
ckanext.spatial.common_map.type = custom
ckanext.spatial.common_map.custom.url = http://tile.openstreetmap.org/{z}/{x}/{y}.png 
ckanext.spatial.common_map.attribution = Map tiles & Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://creativecommons.org/licenses/by-sa/3.0">CC BY SA</a>.
