### ISSUE TITLE
Esri REST viewer can't be created

### ISSUE THREAD

**Issue by jysuh** [ckan/ckanext-geoview#48]
Entered ESRI REST end point to dataset and tried to create new viewer for it but It only shows image as dropdown. See screen shot below:

![image](https://cloud.githubusercontent.com/assets/20560192/17602239/03318422-5fc9-11e6-82fb-54ee4f0c30c0.png)

@Corey Erickson

**Comment by amercader** [comment]
I have 0 experience with the ESRI REST support on this extension but according to [this](https://github.com/ckan/ckanext-geoview/blob/master/ckanext/geoview/plugin.py#L23:L24) the format should be `arcgis_rest` (or maybe `esrigeojson`?)

As I said I'm not sure if the viewer works well with this formats though?

**Comment by jysuh** [comment]
Hmmmm. It is really strange. I intentionally changed format to test999 and then changes to arcgis_rest then click Update Resource button.

![image](https://cloud.githubusercontent.com/assets/20560192/17631386/1f931870-6081-11e6-8512-c30e434b53a4.png)

Then it automatically changed to Esri REST.

![image](https://cloud.githubusercontent.com/assets/20560192/17631483/8135dd2e-6081-11e6-9024-8d22736fa2a7.png)

@Corey Erickson
