### ISSUE TITLE
KML preview doesn't work

### ISSUE THREAD

**Issue by n3tmaster** [ckan/ckanext-geoview#53]
I installed ckanext-geoview following installation instructions.
When I try to open a KML resource, CKAN isn't able to open OpenLayers in order to display my KML.

This is my ckan installation 

http://149.139.16.91:5000/dataset/sir_bike_1

**Comment by drnextgis** [comment]
Cannot open URL.

**Comment by n3tmaster** [comment]
mmm it's strange I just tried the link and it works

can you re-try the link please?

Thank you in advance

**Comment by pduchesne** [comment]
the IP is accessible on port 80, but not 5000.

Are you sure you opened 5000 in your firewall ?

**Comment by n3tmaster** [comment]
I'm sorry, the port 5000 is blocked by our IT manager. I changed the port used by my CKan installation: now it is the 5005.

So the url is : http://149.139.16.91:5005/dataset/sir_bike_1

Thank you in advance

**Comment by amercader** [comment]
Does is work if you manually create the view? ie On the [resource page](http://149.139.16.91:5005/dataset/sir_bike_1/resource/5e13467b-0b6f-4ff2-8395-19c3790e678e)  > Manage > Views > New View > Map Viewer (Open Layers)

If that works you might need to add `geo_view` to the ones that get created automatically when adding a dataset adding this to your ini file:

```
ckan.views.default_views = ... geo_view
```

**Comment by n3tmaster** [comment]
Dear Adrià

thank you for your suggestion, I was able to activate OpenLayer view

but when I select “Preview” function, in order to view Open Layer with my data, i get a void fram (see attached image)


Any idea?

Thank you in advance so much!

Leandro

**Comment by n3tmaster** [comment]
I resolve the issue: I wrote a wrong url into ckan.site_url property.

Now it works. Thank you for the support!
