### ISSUE TITLE
Not able to get the preview of KML files.

### ISSUE THREAD

**Issue by shubham-mahajan** [ckan/ckanext-geoview#58]
Hi Team

I have installed the extension as per readme, but I am not able to get the preview. No error is coming either in JS or in CKAN. Are there any dependencies that I need to install for ckanext-geoview to work properly.

The preview is completely blank page. Attaching the screenshot for the same.

Loading... The text is coming and after that, it went blank.

<img width="1422" alt="screen shot 2018-05-15 at 6 02 15 pm" src="https://user-images.githubusercontent.com/25545982/40100463-05eb3394-58f5-11e8-91d7-4ba9c731ab8b.png">

Thanks

**Comment by pduchesne** [comment]
Hello Shubham,

I tried that resource on a local instance of mine and it worked fine.
can you share a link to an online CKAN instance that reproduces the problem?

**Comment by shubham-mahajan** [comment]
Hi @pduchesne ,

I am also working on local instance only, but if you require I will set up the same in public instance and share the same. The basic difference I am able to see with a working site and my instance are mainly mapconfig options in the inspection of the elements. Is there any dependency on other extension or Framework?

**Comment by pduchesne** [comment]
Can you share your ckanext.spatial.* and ckanext.geoview.* values from your config? And your basemaps.json config, if you have one.

**Comment by shubham-mahajan** [comment]
@pduchesne 

I have not installed the spatial extension, is it required for geoview to work, it's not there in documentation. 

ckan.plugins = stats geo_view text_view image_view resource_proxy
ckan.views.default = image_view geo_view
ckan.spatial.srid = 4326
ckanext.geoview.ol_viewer.formats = wms kml geojson

**Comment by pduchesne** [comment]
OK, I got it.

There's been a regression causing the default basemap to fail. I'll fix that.

In the mean time, to be able to work with your current install, you'll have to explicitly specify a basemap in your config, f.i. : 
```
ckanext.spatial.common_map.type = XYZ
ckanext.spatial.common_map.custom.url = http://tile.openstreetmap.org/{z}/{x}/{y}.png
ckanext.spatial.common_map.attribution = Map tiles & Data by OpenStreetMap, under CC BY SA.
```

**Comment by shubham-mahajan** [comment]
Hi @pduchesne 

Thanks for providing the configuration, it's displaying the display. But default, MAP Viewer(Open Layers) is not getting created for KML files/URLs. Is there any option or configuration entry for default view as MAP Viewer for all the KML files.

P.S.
Configuration entries used are:-

ckan.plugins = stats geo_view text_view image_view resource_proxy
_ckan.views.default = image_view **geo_view**_
ckan.spatial.srid = 4326
ckanext.geoview.ol_viewer.formats = wms kml geojson
ckanext.spatial.common_map.type = custom
ckanext.spatial.common_map.custom.url = http://tile.openstreetmap.org/{z}/{x}/{y}.png
ckanext.spatial.common_map.attribution = Map tiles & Data by OpenStreetMap, under CC BY SA.

**Comment by shubham-mahajan** [comment]
@pduchesne 

Thanks a lot, everything is working fine now. For default view, it was a typo.

**Comment by Ozgur-OZTURK** [comment]
Hi @pduchesne

I installed Ckan version 2.9(https://docs.ckan.org/en/2.9/maintaining/installing/install-from-package.html). Then I installed it with the steps on the link(https://github.com/ckan/ckanext-geoview). But I can't preview geojson file and kml file. My config file same the @shubham-mahajan config file. 
What kind of way should I go to get it working?

Ps. I just installed the ckanext-geoview plugin.
Config file:
ckan.plugins = stats geo_view text_view image_view resource_proxy
ckan.views.default_views = image_view geo_view
ckan.spatial.srid = 4326
ckanext.geoview.ol_viewer.formats = wms kml geojson
ckanext.spatial.common_map.type = custom
ckanext.spatial.common_map.custom.url = http://tile.openstreetmap.org/{z}/{x}/{y}.png
ckanext.spatial.common_map.attribution = Map tiles & Data by OpenStreetMap, under CC BY SA.
