### ISSUE TITLE
Is pip extension version up2date?

### ISSUE THREAD

**Issue by 4estone** [ckan/ckanext-geoview#62]
when I install geoview with pip I'm not sure to install last plugin release. Could you tell me if I'm right or not?
Thanks

Sylvain

**Comment by benhid** [comment]
Latest version from Github is 0.0.16, install by using:

```console
pip install git+https://github.com/ckan/ckanext-geoview.git
```

P.S. Make sure to install any extra requirement from `pip-requirements.txt`:

```console
pip install requests ckantoolkit
```

**Comment by amercader** [comment]
@4estone sorry, it is now: https://pypi.org/project/ckanext-geoview/

@benhid thanks for the pointers
