### ISSUE TITLE
How display map for kml

### ISSUE THREAD

**Issue by student2017USA** [ckan/ckanext-geoview#94]
Hi,

We installed ckanext-geoview.

ckan is starting propelry. What i need to do to show a map? Do i need to store dataset in any speicfic format?

Can you please tell what we do to get map displayed on CKAN?

Thanks so much for your fast help!

**Comment by amercader** [comment]
Please read the README, specifically the OpenLayers Viewer section which is the one that supports rendering KML resources.

https://github.com/ckan/ckanext-geoview#openlayers-viewer
